ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG NVIDIA_DRIVER_VERSION="610.57.04"

RUN curl -sSL https://developer.download.nvidia.com/compute/cuda/repos/fedora44/x86_64/cuda-fedora44.repo \
    -o /etc/yum.repos.d/cuda-fedora44.repo

COPY mok/MOK.der /var/lib/dkms/mok.pub

RUN --mount=type=secret,id=mok_key,target=/var/lib/dkms/mok.key \
    KERNEL_VERSION=$(rpm -q kernel --qf "%{VERSION}-%{RELEASE}.%{ARCH}") && \
    dnf install -y \
    kernel-devel-${KERNEL_VERSION} \
    kernel-headers \
    dkms \
    kmod-nvidia-open-dkms-${NVIDIA_DRIVER_VERSION}* \
    nvidia-driver-${NVIDIA_DRIVER_VERSION}* \
    nvidia-driver-cuda-${NVIDIA_DRIVER_VERSION}* \
    nvidia-settings-${NVIDIA_DRIVER_VERSION}* \
    && \
    dkms autoinstall -k "${KERNEL_VERSION}" && \
    rpm -e --nodeps dkms && \
    dnf clean all

# Wayland Modesetting & Framebuffer Direct Rendering
# modeset=1 + fbdev=1 enables smooth Wayland rendering, VRR/G-Sync, and prevents stutter
RUN echo "options nvidia-drm modeset=1 fbdev=1" > /etc/modprobe.d/nvidia.conf

# Enable Power Management
RUN systemctl enable nvidia-suspend.service \
    nvidia-resume.service \
    nvidia-hibernate.service
